# Author: Hans Liljestrand <hans@liljestrand.dev>
# Copyright: Secure Systems Group, Aalto University, https://ssg.aalto.fi
#
# This code is released under Apache 2.0 license

USE_PAUTH = yes
USE_BECFI = yes
USE_FECFI = yes
USE_DPI = yes

O_LEVEL = 2

# pull in common configuration
include ../Makefile.common
